# Generated by Django 5.1.1 on 2024-10-21 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_categoria_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='proveedor',
            table='proveedor',
        ),
    ]
