# Generated by Django 5.1.2 on 2024-10-22 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_producto_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table='producto',
        ),
    ]
