# Generated by Django 5.1 on 2024-10-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=128)),
                ('telefono', models.CharField(max_length=20)),
                ('correo_proveedor', models.EmailField(max_length=250)),
            ],
        ),
    ]
