# Generated by Django 5.1 on 2024-10-07 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_movimientoempleado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientoempleado',
            options={'permissions': [('view_movimiento_empleado_history', 'Puede ver el historial de movimientos de empleados')]},
        ),
    ]
