# Generated by Django 5.1 on 2024-10-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_sucursal_profile_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='direccion',
            field=models.CharField(default='no especificada', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(choices=[('cafeteria', 'Cafetería'), ('heladeria', 'Heladería')], max_length=20, unique=True),
        ),
    ]
