# Generated by Django 5.1 on 2024-09-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_empleados_apellidos_emp_empleados_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
