# Generated by Django 5.1.1 on 2024-10-21 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_producto_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sucursal',
            table='sucursal',
        ),
    ]
